### ISSUE TITLE
Duplicated files in Coveralls

### ISSUE THREAD

**Issue by ronisbr** [JuliaCI/Coverage.jl#245]
Hi!

All my files are repeated 6 times in Coveralls analysis: https://coveralls.io/github/JuliaSpace/SatelliteToolbox.jl?branch=master. This does not happen with Coverage. I think this must be related to the fact that I was testing against 6 Julia versions. Is it expected?

I am using Coverage analysis by the native support in Travis:

```

language: julia

os:
    - linux
    - osx

julia:
    - 1.0
    - 1.2
    - nightly

codecov: true
coveralls: true

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip
```
